version: '3'
services:
  influxdb:
    image: influxdb:latest
    environment:
      INFLUXDB_ADMIN_USER: "${INFLUXDB_ADMIN_USER}"
      INFLUXDB_ADMIN_PASSWORD: "${INFLUXDB_ADMIN_PASSWORD}"
    ports:
      - "8083:8083"
      - "8086:8086"
    restart: unless-stopped
    volumes:
      - influxdb-data:/var/lib/influxdb
  rtl-433-importer:
    image: brannondorsey/rtl-433-influxdb-importer
    build:
      context: .
    command:
      - python
      - influxdb_import.py
      - --user=${INFLUXDB_ADMIN_USER}
      - --password=${INFLUXDB_ADMIN_PASSWORD}
      - --host=${INFLUXDB_HOST}
      - --station=${STATION_NAME}
      - --input=/root/packets.json
    restart: unless-stopped
    volumes:
      - "${INPUT_FILE}:/root/packets.json"
    links:
      - influxdb
volumes:
  influxdb-data:
    driver: local
