version: '3'
services:
  influxdb:
    image: influxdb:latest
    environment:
      INFLUXDB_ADMIN_USER: "${INFLUXDB_ADMIN_USER}"
      INFLUXDB_ADMIN_PASSWORD: "${INFLUXDB_ADMIN_PASSWORD}"
    ports:
      - "8083:8083"
      - "8086:8086"
    restart: unless-stopped
    volumes:
      - influxdb-data:/var/lib/influxdb
  rtl-433-importer:
    image: brannondorsey/rtl-433-influxdb-importer
    build:
      context: .
    environment:
      PYTHONUNBUFFERED: "1"
    command:
      - python
      - influxdb_import.py
      - --user=${INFLUXDB_ADMIN_USER}
      - --password=${INFLUXDB_ADMIN_PASSWORD}
      - --host=${INFLUXDB_HOST}
      - --station=${STATION_NAME}
      - --input=/root/packets.json
      ## Uncomment these bottom two lines to initialize the database and fill it with
      ## existing weather data from ${INPUT_FILE}
      # - --create-and-overwrite-db
      # - --backfill
    restart: unless-stopped
    volumes:
      - "${INPUT_FILE}:/root/packets.json"
## Uncomment if influxdb and rtl-433-importer live on different hosts
#    network_mode: host # useful if influxdb is running on another host
volumes:
  influxdb-data:
    driver: local
